export const primary = 'orange'
export const secondary = 'white'
export const tertiary = '#012e40'
export const quaternary = 'lightgray'
export const quinary = '#1a1a1a'
export const senary = 'black'
export const septenary = '#f9e98b'