export const primary = 'orange'
export const secondary = 'white'
export const tertiary = '#012e40'
export const quaternary = 'lightgray'
export const quinary = 'grey'
export const senary = 'black'
export const septenary = 'lightblue'